Twitter/config/routes.rb
Twitter::Application.routes.draw do
  devise_for :users
  resources :home
  resources :profile
  resources :connection
  resources :notification
  root :to => 'home#index'
end

Twitter/app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :follower, :class_name => "User"
  belongs_to :following, :class_name => "User"
  attr_accessible :follower, :following
end

Twitter/app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :to, :class_name => "User"
  belongs_to :from, :class_name => "User"
  attr_accessible :note_type, :to, :from
end

Twitter/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :mobile
  # attr_accessible :title, :body
  has_many :user_tweets
end

Twitter/app/models/user_tweet.rb
class UserTweet < ActiveRecord::Base
  belongs_to :user
  attr_accessible :tweet, :user
end

Twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

Twitter/app/controllers/connection_controller.rb
class ConnectionController < ApplicationController
  before_filter :authenticate_user!



  def index
    @following_list=Connection.where(:follower_id => current_user.id)
    @follower_list=Connection.where(:following_id => current_user.id)
  end

  def create
    user=User.find_by_email params[:email]
    if user.nil?
      flash[:notice]="username not found!"
      redirect_to connection_index_path
    elsif params[:email] == current_user.email
      flash[:notice]="Cannot follow yourself!"
      redirect_to connection_index_path
      return
    end


    connection=Connection.find_by_following_id_and_follower_id  current_user.id, user.id
    if connection.nil?
      n=Notification.find_by_to_id_and_from_id_and_note_type(current_user.id, user.id, "request")
      if n.nil?
        redirect_to notification_index_path
      else

        connection=Connection.new
        connection.follower=user
        connection.following=current_user
        connection.save

        n.from=current_user
        n.to=user
        n.note_type="accept"
        n.save
        redirect_to notification_index_path
        return
      end

      flash[:notice]="already a follower!"
      redirect_to connection_index_path

    end
  end


  def update
    begin
      connection=Connection.find params[:id]
      connection.destroy
    rescue ActiveRecord::RecordNotFound
      puts params[:id]
    end
    redirect_to connection_index_path
  end

end

Twitter/app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_filter :authenticate_user!


  def index
    if params[:page].nil?
      @page=1
    else
      @page=Integer(params[:page])
    end
    connection=Connection.find_all_by_follower_id current_user.id
    search=[]
    connection.each do|c|
      search.append c.following_id
    end
    search.append current_user.id
    @tweet_list= UserTweet.where(:user_id => search).order("created_at DESC").paginate(:page => params[:page],:per_page => 10)

  end


  def create
    if params[:tweet].strip==""
      flash[:status]="Blank tweet cannot be posted..."
      redirect_to home_index_path
      return
    end
    flash[:status]="Tweet successfully posted!"
    UserTweet.create(tweet: params[:tweet], user: current_user)

    redirect_to home_index_path


  end
end

Twitter/app/controllers/notification_controller.rb
class NotificationController < ApplicationController
  before_filter :authenticate_user!
  def index
    @notes= Notification.order("updated_at DESC").find_all_by_to_id current_user.id
  end

  def create
    user=User.find_by_email params[:email]

    if user.nil?
      flash[:notice]="username not found!"
      redirect_to connection_index_path
      return
    end

    if params[:type]=="request"
      if params[:email] == current_user.email
        flash[:notice]="Cannot follow yourself!"
        redirect_to connection_index_path
        return
      end
      c=Connection.find_by_following_id_and_follower_id(user.id, current_user.id)
      if !c.nil?
        flash[:notice]="Already Following!"
        redirect_to connection_index_path
        return
      end
      n=Notification.create! to: user, from: current_user, note_type: "request"

      flash[:notice]="Request sent!"
      redirect_to connection_index_path
    elsif params[:type]=="Decline"
      n=Notification.find_by_to_id_and_from_id(current_user.id,user.id)
      if n.nil?
        redirect_to notification_index_path
        return
      end

      n.to=user
      n.from=current_user
      n.note_type="decline"
      n.save
    end
    redirect_to notification_index_path
  end

end

Twitter/app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  def index
    begin
      @user=User.find params[:user_id]
    rescue ActiveRecord::RecordNotFound
      @user=nil
    end
  end
end

Twitter/app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController

  def new
    super
  end

  def create
    super

  end

  def edit
    super

  end

end

Twitter/app/helpers/application_helper.rb
module ApplicationHelper
end

Twitter/app/helpers/connection_helper.rb
module ConnectionHelper
end

Twitter/app/helpers/home_helper.rb
module HomeHelper
end

Twitter/app/helpers/notification_helper.rb
module NotificationHelper
end

Twitter/app/helpers/profile_helper.rb
module ProfileHelper
end

Twitter/app/helpers/registration_helper.rb
module RegistrationHelper
end

Twitter/app/views/connection/index.html.erb
<h3>Following</h3>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Action</th>
  </tr>
  <% @following_list.each do|f| %>
  <tr>
    <% user=f.following %>
    <td><%= user.name %></td>
    <td><a href="<%= profile_index_path %>?user_id=<%= user.id %>"> <%= user.email %></a></td>
    <td><%= form_tag(connection_path(f.id), method: "put") do %>
          <%= submit_tag("UnFollow")
          %>
      <% end %></td>

  </tr>
  <% end %>
</table>
<div>
  <%= form_tag(notification_index_path, :method => "post") do %>
      <%= label_tag(:label, "username: ") %>
      <%= hidden_field_tag(:type, "request") %>
      <%= text_field_tag(:email) %>
      <%= submit_tag("Add") %>
  <% end %>
  <% if flash[:notice]!=nil %>
    <p><%= flash[:notice] %></p>
  <% end %>
</div>

<div>
  <h3>Followers</h3>
  <table border="1">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Date</th>
    </tr>
    <% @follower_list.each do|f| %>
        <tr>
          <% user=f.follower %>
          <td><%= user.name %></td>
          <td><a href="<%= profile_index_path %>?user_id=<%= user.id %>"> <%= user.email %></a></td>
          <td><%= user.created_at %></td>

        </tr>
    <% end %>
  </table>

</div>

Twitter/app/views/home/index.html.erb
<div>
  <%= form_tag(home_index_path, method: "post") do %>
      <%= label_tag(:label, "Tweet") %>
      <%= text_field_tag(:tweet) %>
      <%= submit_tag("Post") %>
  <% end %>
</div>

<% if flash[:status]!=nil %>
    <div>
      <p><%= flash[:status] %></p>
    </div>
<% end %>
<div>
  <p>Recent Tweets</p>
  <table border="1">
    <tr>
      <th>Username</th>
      <th>Tweet</th>
      <th>time</th>
    </tr>

    <% @tweet_list.each do |tweet| %>
    <tr>
      <td> <%= (User.find tweet.user_id).email %> </td>
      <td> <%= tweet.tweet %> </td>
      <td> <%= tweet.created_at %> </td>
    </tr>
     <% end %>


  </table>
  <% if @tweet_list.length==0 %>
    <p>No more Tweets</p>
  <% end %>
  <%= will_paginate @tweet_list %>


</div>

Twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>



<% if user_signed_in? %>
    <h1>Welcome</h1>
    <div>
      <a href="<%= home_index_path %>">Home</a>
      <a href="<%= notification_index_path %>">Notifications</a>
      <a href="<%= connection_index_path %>">Connections</a>
      <span>Welcome</span>
      <a href="<%= profile_index_path %>?user_id=<%= current_user.id %>"><%= current_user.email %></a>
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
    </div>
<% end %>

<%= yield %>

</body>
</html>

Twitter/app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
    <h1>Welcome</h1>
    <div>
      <a href="<%= home_index_path %>">Home</a>
      <a href="#">Connections</a>
      <span>Welcome</span>
      <a href="#"><%= current_user.email %></a>
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
    </div>
<% end %>

<%= yield %>

</body>
</html>

Twitter/app/views/notification/index.html.erb
<h2>Notifications</h2>
<div>
<% if @notes.length!=0 %>
    <table>
    <% @notes.each do|n| %>
        <tr>
          <% if n.note_type=="request" %>
              <td>
                User <%= n.from.email %> has requested to follow you.
                </td>
              <td>
              <%= form_tag(connection_index_path, method: "post") do %>
                <%= hidden_field_tag(:email, n.from.email) %>
                  <%= submit_tag("Accept", name: "type") %>
                <% end %>
              </td>
                <td>
                  <%= form_tag(notification_index_path, method: "post") do %>
                      <%= hidden_field_tag(:email, n.from.email) %>
                      <%= submit_tag("Decline", name: "type") %>

                      <% end %>
                </td>
          <% elsif n.note_type=="decline" %>
            <td>
              User <%= n.from.email %> has declined your request.
            </td>
          <% elsif n.note_type=="accept" %>
              <td>
                User <%= n.from.email %> has accepted your request.
              </td>

          <% end %>
        </tr>


    <% end %>
    </table>

    <% else %>
  <p> No Notifications</p>
<% end %>

</div>